### ISSUE TITLE
Problem with relationship architecture

### ISSUE THREAD

**Issue by shunjid** [mkshuvo/mlebs#1]
Hi,

So far, analyzing your project, I have come to know that a timeslot (Timeslot.cs) can have multiple bookings and a booking can have only one timeslot which is eventually a (**one-to-many** relationship). And this relationship with booking also applies to Equipment, User and Lab as well.

What you are doing in Equipment, Timeslot, Lab, User class is initializing ICollection<Booking> in constructor. That shouldn't create any problem defining the relationship. What makes your relationship critical is you are trying to add Id of **Equipment, Timeslot, Lab, User** manually by putting:

```
        public string MemberID { get; set; }
        public string LabID { get; set; }
        public string EquipmentID { get; set; }
        public string SlotID { get; set; }
```

This is not the flexible design to create a one-to-many relationship. Instead of these four attributes you should go with next four attributes:

```
        public ApplicationUser ApplicationUsers { get; set; }
        public Lab Labs { get; set; }
        public Equipment Equipments { get; set; }
        public Timeslot Timeslots { get; set; }
```

### **Now the question comes, why should you go with these four?**

-  Because this is the correct design to bring their ID as a foreign key in Booking table
-  While re-furnishing front-end and controllers it will make your task easier to deal with other four classes. Let's say you are trying to bring all the Bookings to View in a **/Timeslot/Details** then in **TimeslotsController**'s Details method you can easily add all the bookings in a ViewBag like:

```
var timeslot = await _context.Timeslot.FirstOrDefaultAsync(m => m.Id == id);
ViewBag.bookings = await _context.Booking.Where(x => x.Timeslot == timeslot).ToListAsync();
```

And the getting all the values of ViewBag.bookings in front-end of /Timeslots/Details will be easier to get like:

```
 @{
    var bookingList = ViewBag.bookings as IEnumerable<Booking>;
}
```

If removing manual Id in Booking doesn't work then try to remove constructors in all other four classes and Instead of ICollection use List.

**#HappyProgramming** 
Shunjid,
B22-SWE

**Comment by mkshuvo** [comment]
Okay. If I only use these,

`public ApplicationUser ApplicationUsers { get; set; }
        public Lab Labs { get; set; }
        public Equipment Equipments { get; set; }
        public Timeslot Timeslots { get; set; }`

Instead of these,
`public string MemberID { get; set; }
        public string LabID { get; set; }
        public string EquipmentID { get; set; }
        public string SlotID { get; set; }`

Then I do not get input fields for them in the view when I try to generate controllers with the view.

**Comment by mkshuvo** [comment]
Sorry. I think I understand why it doesn't link or creates a Successful table relationship with each other. In the Equipment, Lab, ApplicationUser classes I have one `public int Id { get; set; }` with a  `[Key]` annotation. Then in each class under this `public int Id { get; set; }` property I have another ID property in a format like this `public int ClassNameId { get; set; }` e.g. `public int EmployeeId { get; set; }` , `public int LabId { get; set; }`. 

I checked another project's model. The topic is different but somehow model creation was correct by mistake :) . When I generated view there, I saw a drop-down in the ID selection, while in my mlebs project I had to put manually with a TextBox input field.

Then I came to realize this fact.

**Comment by shunjid** [comment]
Yes, you got the point of your mistake. Best of luck :+1:

**Comment by mkshuvo** [comment]
One more problem with this relationship of models. I can not create a relationship with ApplicationUser class i.e AspnetUsers table. I can make model relation with others just fine now but this table is default or builtin in asp.net core. When I use this `public ApplicationUser ApplicationUsers { get; set; }` in Booking class it creates a column called "ApplicationUsersId" in ApspnetUsers table. Can you please help me with this problem?

**Comment by shunjid** [comment]
@mkshuvo To handle relation with AspnetUsers table you need to deal with these **NuGet** packages below:
-  Microsoft.AspNetCore.Identity
-  Microsoft.AspNetCore.Identity.EntityFrameworkCore
-  Microsoft.EntityFrameworkCore.Design

And then handle the identity, user-session with UserManager and SignInManager namespaces through user defined controller like:

```
private readonly UserManager<IdentityUser> _userManager;
private readonly SignInManager<IdentityUser> _signInManager;

        public AccountController(UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }
```

Best of Luck :+1:
